### ISSUE TITLE
Handling for renamed projects

### ISSUE THREAD

**Issue by nschonni** [Microsoft/Code-Search#33]
Although I think this may be related to a refresh job that never finishes correctly, we see results from both the old project name and the new project name.
Is there any steps to follow to correct this? EX: push and resume indexing?

**Comment by bittusarkar** [comment]
This is by design. Once a project is renamed, new documents are indexed with the new name and after that documents with old project name are deleted. So, there would be an intermediate time period when results from both new and old name will be returned. This is not related to the scripts in this repository. Please file an issue at [https://developercommunity.visualstudio.com/content/problem/post.html?space=22]() to get better traction.
